### ISSUE TITLE
I can't get alert titles to work

### ISSUE THREAD

**Issue by davesag** [eltimn/jquery-bs-alerts#2]
My alert div is formatted as follows: (in a `Jade` template)

```
    #error-display(data-alerts="alerts", data-titles="{'error': '<h3>Error</h3>'}")
```

The alerts are initialised in Javascript via

```
    $("#error-display").bsAlerts();
```

And in my error handler I call

```
     $(document).trigger("add-alerts", [{message: err.responseJSON.message, priority: 'error'}]);
```

The alert div shows and the error message is displayed just fine, but the title doesn't show up.

What am I doing wrong?

**Comment by eltimn** [comment]
@davesag turns out the problem was with using single quotes in the titles JSON as @zacechola hinted at. JSON requires double quotes around keys and strings.

To fix your code, you'd need:

     #error-display(data-alerts="alerts", data-titles='{"error": "<h3>Error</h3>"}')

Apologies for having bad examples. They've been updated.
