### ISSUE TITLE
IE8 Trim Issue

### ISSUE THREAD

**Issue by speshulk926** [eltimn/jquery-bs-alerts#4]
I know IE8 is old and shouldn't be supported, but I found this bug and it is really easy to fix.  I got the following error:
![image](https://cloud.githubusercontent.com/assets/611769/4034527/846dc65e-2c86-11e4-9d6e-dc0255c4cb42.png)

I started doing some searching and found this article that says IE8 doesn't support {property}.trim(), but you could use $.trim({property}).
http://stackoverflow.com/questions/5173828/how-to-deal-with-ie8-jquery-object-doesnt-support-this-property-or-method-error

I changed my local code to do this.  You had one section that used it and I changed it from

var a=r.trim();

to 

var a = $.trim(r);

Now it works in IE8 too! =)

**Comment by eltimn** [comment]
Fixed with d7f0d0340545184e7129389ebb43c09d90e05c4d
