### ISSUE TITLE
Examples not working right now ?

### ISSUE THREAD

**Issue by gtzinos** [eltimn/jquery-bs-alerts#5]

**Comment by eltimn** [comment]
Hi,

Are you referring to the demo website? If so, I haven't had a chance to update that since Cloudbees shut down their service.

If you mean locally, then it sounds like there may be a problem. Could you give more details?

**Comment by gtzinos** [comment]
Hello,
was for the demo website. So you will fix them ?

**Comment by eltimn** [comment]
Originally I thought you were referring to the examples at [lift-extras](https://github.com/eltimn/lift-extras), but now I'm not sure.

I've just updated the docs site for this library and the examples seem to work fine. If you were referring to lift-extras, that's still a work in progress, but I just need a place to deploy it now.

If this is still a problem, please re-open and give more details. Thanks.
